# This is already included in the 2-gowebapp-deployment.yaml but broken out for reference

kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: goweb-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`go.dev.fsa.lab`)
    kind: Rule
    services:
    - name: gowebapp
      port: 80
